### ISSUE TITLE
The JSONP callback parameter is not in an acceptable format.

### ISSUE THREAD

**Issue by kbdavis07** [elmah/elvue#1]
Hi,
Just installed Elvue and getting the following error message:
#### System.ExceptionThe JSONP callback parameter is not in an acceptable format.

`System.Exception: The JSONP callback parameter is not in an acceptable format.
   at Elmah.ErrorLogDownloadHandler.JsonPaddingFormat.Header() at Elmah.ErrorLogDownloadHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData) at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)`

**Comment by atifaziz** [comment]
That happens when the `callback` value fails the following [regex expression](https://bitbucket.org/project-elmah/1x/src/3a71f9a4eeb57921662b5a5acc211fc4b0932cae/src/Elmah/ErrorLogDownloadHandler.cs?at=v1.2-sp2&fileviewer=file-view-default#ErrorLogDownloadHandler.cs-311) test:

```
^    [a-z_] [a-z0-9_]+ ( \[ [0-9]+ \] )?
( \. [a-z_] [a-z0-9_]+ ( \[ [0-9]+ \] )? )* $
```

Examples of permitted forms are:
- `foo`
- `foo.bar`
- `foo[42].bar`
- `foo.bar[42]`
- `foo.bar.baz`
- …and so on

What does your `callback` look like?

**Comment by kbdavis07** [comment]
http://localhost:61460/errors/download?format=jsonp&callback=parent.onerrors002limit=250

**Comment by atifaziz** [comment]
Are you not missing an ampersand to separate `limit`? Assuming your callback is called `onerrors002`, I would say the URL should then read:

```
http://localhost:61460/errors/download?format=jsonp&callback=parent.onerrors002&limit=250
```

**Comment by atifaziz** [comment]
Would also recommend reading “[Error Log Download Applications](https://elmah.github.io/a/error-log-download-applications/)” if you need some background to Elvue. The link in the README was bad & which I just [fixed](https://github.com/elmah/elvue/commit/670e950d97ac93553c67730790b30a9caa91b602).

**Comment by kbdavis07** [comment]
That works, but why is Elmah leaving out the "&"  ?

Steps that I install:
1. Install-Package elmah.bootstrapper -Pre
2. Copy elvue.html and elvue.js to a location within a web application where ELMAH is deployed 
   Next, add a JavaScript file named elvuecfg.js 

`configured (the handler registration is required)`  That might be the issue? What needs to be configured exactly?

**Comment by atifaziz** [comment]
If you have Bootstrapper installed then it should do the handler registration automatically & dynamically. Did you configure it to a different URL for than handler part? Did you update `config.src` in `elvuecfg.js` accordingly? Bootstrapper by default registers the handler to respond at `elmah`, `errors` or `errorlog` under your web app root so at a minimum the `elvuecfg.js` should read:

``` js
config = {
  src: 'errorlog/download'
};
```

**Comment by kbdavis07** [comment]
Seems like this might be the issue?

``` javascript
$scope.src = (function(src, limit){
      return (src + "?format=jsonp&callback=CALLBACK") + (limit > 0 ? "&limit=" + limit : '');
    }.call(this, config.src || 'elmah.axd/download', +config.limit));
    y$ = $scope; 
```

**Comment by kbdavis07** [comment]
``` javascript
config = {
    src: '/errors/download', // location of log download URL
    title: 'TITLE',            // report title
    limit: 250                 // limit report to these most recent errors
};
```

**Comment by kbdavis07** [comment]
change it to /errorslog same thing.

I have a feeling about the javascript?

**Comment by atifaziz** [comment]
It should be `errorlog`, not `errorslog` but never mind that. I think the issue might be elsewhere. Have you tried with commenting out the `limit` configuration?

I checked out the JavaScript & just from reading, I see that it's adding the `&` if `limit` is there:

``` js
(limit > 0 ? "&limit=" + limit : '')
```

**Comment by atifaziz** [comment]
I have a feeling it might be a bug later on in this piece of the JavaScript:

``` js
src.replace(/=CALLBACK(&|$)/, "=parent." + encodeURIComponent(callback))
```

The ampersand is being eaten up by the replacement when `&limit` is there.

**Comment by kbdavis07** [comment]
That is what I am thinking :smile:

**Comment by kbdavis07** [comment]
When I took out the limit it is now trying to download the file instead of displaying it.

**Comment by kbdavis07** [comment]
Commenting out the limit in config seems to make it work.

``` javascript

config = {
    src: '/errors/download', // location of log download URL
    title: 'TITLE',            // report title
    //limit: 250                 // limit report to these most recent errors
};
```

**Comment by atifaziz** [comment]
I have managed to reproduce this on my end so converting this into a bug issue.

**Comment by kbdavis07** [comment]
So the issue is with the limit for some reason it is leaving out the  `&`

**Comment by kbdavis07** [comment]
So for now that would do till you fix it :smile:

**Comment by kbdavis07** [comment]
Screenshot:

http://awesomescreenshot.com/0845kpn272

**Comment by atifaziz** [comment]
Should be fixed now. Let me know if it's still not working on your end. Otherwise thanks for reporting this.

**Comment by kbdavis07** [comment]
That fixed it :+1:

**Comment by kbdavis07** [comment]
Thanks for your help and quick response have a great day and continue your great work!
