### ISSUE TITLE
elvue screenshot is missing

### ISSUE THREAD

**Issue by ShaneCourtrille** [elmah/elvue#2]
When looking at the explanation on github there is a screenshot that is missing.

**Comment by atifaziz** [comment]
The address of the screenshot no longer seems to be service it. This is what it's supposed to be:

![elvue](https://cloud.githubusercontent.com/assets/20511/17787802/fef0f6d2-658a-11e6-9d49-65cb93becf56.png)

I'll fix the README shortly & thanks for reporting this.
