### ISSUE TITLE
elvue in ASP.NET 4.6.1

### ISSUE THREAD

**Issue by kiquenet** [elmah/elvue#3]
I have webapp  ASP.NET 4.6.1. 

Several questions for me, I'm newbie with ELMAH.

How-to use elvue? 

HOW-TO secure access to  elvue.html  and  elvuecfg.js  in ASP.NET (if is possible use elvue in ASP.NET)?

How-to securize elmah.axd?

inurl:elmah.axd "Error log for" in Google
https://www.google.es/search?hl=en&q=inurl:elmah.axd+%22Error+log+for%22&gws_rd=cr,ssl&ei=NBYmWM2sBcvzUsyGiLgK

bad practices using allowRemoteAccess  attribute in ELMAH (http://geeks.ms/lruiz/2014/07/21/asp-net-revisa-la-configuracin-de-elmah-en-produccin/)

**Comment by atifaziz** [comment]
> How-to use elves?

Hmm…this is hopefully [covered in the `README`](https://github.com/elmah/elvue/blob/63df7e6f20d9ed3c6f2f53f09dbc1546e8ad45d0/README.md). 🤔 For more detailed background, see [ELMAH Error Log Download Applications](https://elmah.github.io/a/error-log-download-applications/).

> HOW-TO secure access to elvue.html and elvuecfg.js in ASP.NET (if is possible use elvue in ASP.NET)?

Just use IIS security configuration options.

> bad practices using `allowRemoteAccess` attribute in ELMAH

Yes, don't just blindly set it to `true`.

For more advanced scenarios, like [only allowing requests from certain IP addresses](https://github.com/elmah/Sandbox/blob/c135b9a5a99f6c38d87dc97f2e8a2b99d91d3276/src/Sandbox/NetworkAuthorizationModule.cs), implement an `IRequestAuthorizationHandler`. For more background and details, see the “[Implementing more advanced authorization rules for web-based ELMAH error log](https://groups.google.com/forum/#!msg/elmah/Ug2cyCcXbYU/Ok2aBdVrwLsJ)” thread from the [ELMAH Discussion Group](http://groups.google.com/group/elmah).

---

If your questions are answered, consider closing this issue.
